# Site Configuration
title: "Ouroboros"
tagline: "By Aayush Agrawal"
description: >-
  Personal blog of Aayush Agrawal — Thoughts on Serpents and Loops, Yin and Yang, Recursion and Absurdity.
url: "https://ouroboros.aayushagrawal.me"
baseurl: ""

# Theme settings
theme: jekyll-theme-lanyon

# Build settings
markdown: kramdown
permalink: /posts/:title/
paginate: 5
excerpt_separator: "<!--more-->"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
